version: '2'
services:
  lgogdownloader:
    build: .
    image: graag/lgogdownloader
    volumes:
      - "$HOME/.cache/lgogdownloader:/home/user/.cache/lgogdownloader"
      - "$HOME/.config/lgogdownloader:/home/user/.config/lgogdownloader"
      - "$GOG_DIR:/home/user/GOG"
